### PR TITLE
xfce4 notify theme for Paper

### PR DESCRIPTION
**Pull request by blasterbug**
a file to make XFCE4 notify able to use Paper theme

### CODE REVIEW

**Comment by blasterbug** [comment]
up

**Comment by blasterbug** [comment]
Make XFCE4 notify able to use Paper theme

**Comment by snwh** [comment]
The colours you have in the ```gtkrc``` file are not exactly the ones used in Paper. I would suggest poking around in the gtk3 css to make these notifications exactly right, for instance the ```gtk-dark.css``` would have the correct colours if these are to be dark notifications.

**Comment by blasterbug** [comment]
It's done, I update the colors using the ones used for gnome-shell notifications.

**Comment by blasterbug** [comment]
done!

**Pull request merged**
